### ISSUE TITLE
Support default config 

### ISSUE THREAD

**Issue by 4U6U57** [dein0s/dotbot_plugin_aptget#7]
I'd like to have all my packages upgraded each time without having to put `upgrade: true` on all of them. 

Example config:
```yaml
defaults:
    aptget:
        upgrade: true

sudo:
  - aptget:
        aptitude:
        curl:
```
